In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [ ]:
dados_2022 = pd.read_excel('../BASES/BASE DE DADOS PEDE 2024 - DATATHON.xlsx', sheet_name = 'PEDE2022')
dados_2023 = pd.read_excel('../BASES/BASE DE DADOS PEDE 2024 - DATATHON.xlsx', sheet_name = 'PEDE2023')
dados_2024 = pd.read_excel('../BASES/BASE DE DADOS PEDE 2024 - DATATHON.xlsx', sheet_name = 'PEDE2024')

In [ ]:
## A primeira solução visa unir normalizar os dataframes e unir apenas as colunas que existem nos 3

##Criação da coluna "ano"
dados_2022['ano'] = '2022'
dados_2023['ano'] = '2023'
dados_2024['ano'] = '2024'

##Alteração do nome das colunas da base de 2022, 2023 e 2024
dados_2022.rename(columns = {'Ano nasc' : 'Data de Nasc' ,
'Defas' : 'Defasagem' ,
'Inglês' : 'Ing' ,
'Matem' : 'Mat' ,
'Nome' : 'Nome Anonimizado' ,
'Portug' : 'Por' ,
'Idade 22' : 'Idade' ,
'Pedra 22' : 'Pedra atual' ,
'INDE 22' : 'INDE atual',
'Fase ideal': 'Fase Ideal'
}, inplace = True)

dados_2023.rename(columns = {'Pedra 2023' : 'Pedra atual' ,
'INDE 2023' : 'INDE atual'
}, inplace = True)

dados_2024.rename(columns = {'Pedra 2024' : 'Pedra atual' ,
'INDE 2024' : 'INDE atual'
}, inplace = True)

## Seleção das colunas que existem nas 3 bases
dados_2022_padronizado = dados_2022[['Ano ingresso','Atingiu PV','Avaliador1','Avaliador2','Avaliador3','Avaliador4','Cf','Cg','Ct','Data de Nasc','Defasagem','Destaque IDA','Destaque IEG','Destaque IPV','Fase','Fase Ideal','Gênero','IAA','IAN','IDA','Idade','IEG',
'INDE atual','Indicado','Ing','Instituição de ensino','IPS','IPV','Mat','Nº Av','Nome Anonimizado','Pedra 20','Pedra 21','Pedra atual','Por','RA','Rec Av1','Rec Av2','Rec Psicologia','Turma','ano']]

dados_2023_padronizado = dados_2023[['Ano ingresso','Atingiu PV','Avaliador1','Avaliador2','Avaliador3','Avaliador4','Cf','Cg','Ct','Data de Nasc','Defasagem','Destaque IDA','Destaque IEG','Destaque IPV','Fase','Fase Ideal','Gênero','IAA','IAN','IDA','Idade','IEG',
'INDE atual','Indicado','Ing','Instituição de ensino','IPS','IPV','Mat','Nº Av','Nome Anonimizado','Pedra 20','Pedra 21','Pedra atual','Por','RA','Rec Av1','Rec Av2','Rec Psicologia','Turma','ano']]

dados_2024_padronizado = dados_2024[['Ano ingresso','Atingiu PV','Avaliador1','Avaliador2','Avaliador3','Avaliador4','Cf','Cg','Ct','Data de Nasc','Defasagem','Destaque IDA','Destaque IEG','Destaque IPV','Fase','Fase Ideal','Gênero','IAA','IAN','IDA','Idade','IEG',
'INDE atual','Indicado','Ing','Instituição de ensino','IPS','IPV','Mat','Nº Av','Nome Anonimizado','Pedra 20','Pedra 21','Pedra atual','Por','RA','Rec Av1','Rec Av2','Rec Psicologia','Turma','ano']]

In [ ]:
dados_2022_padronizado

,Ano ingresso,Atingiu PV,Avaliador1,Avaliador2,Avaliador3,Avaliador4,Cf,Cg,Ct,Data de Nasc,...,Pedra 20,Pedra 21,Pedra atual,Por,RA,Rec Av1,Rec Av2,Rec Psicologia,Turma,ano
0,2016,Não,Avaliador-5,Avaliador-27,Avaliador-28,Avaliador-31,18,753,10,2003,...,Ametista,Ametista,Quartzo,3.5,RA-1,Mantido na Fase atual,Promovido de Fase + Bolsa,Requer avaliação,A,2022
1,2017,Não,Avaliador-5,Avaliador-27,Avaliador-28,Avaliador-31,8,469,3,2005,...,Ametista,Ametista,Ametista,4.5,RA-2,Promovido de Fase,Promovido de Fase + Bolsa,Sem limitações,A,2022
2,2016,Não,Avaliador-5,Avaliador-27,Avaliador-28,Avaliador-31,13,629,6,2005,...,Ametista,Ametista,Ágata,4.0,RA-3,Promovido de Fase,Promovido de Fase + Bolsa,Sem limitações,A,2022
3,2017,Não,Avaliador-5,Avaliador-27,Avaliador-28,Avaliador-31,15,731,7,2005,...,Ametista,Ametista,Quartzo,3.5,RA-4,Promovido de Fase,Mantido na Fase atual,Requer avaliação,A,2022
4,2016,Não,Avaliador-5,Avaliador-27,Avaliador-28,Avaliador-31,6,344,2,2005,...,Ametista,Ametista,Ametista,2.9,RA-5,Promovido de Fase,Promovido de Fase + Bolsa,Requer avaliação,A,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,2022,Não,Avaliador-11,Avaliador-3,NaN,NaN,10,48,3,2015,...,NaN,NaN,Topázio,8.2,RA-856,Promovido de Fase,Mantido na Fase atual,Não atendido,Z,2022
856,2022,Sim,Avaliador-11,Avaliador-3,NaN,NaN,27,97,5,2013,...,NaN,NaN,Topázio,9.3,RA-857,Promovido de Fase,Mantido na Fase atual,Não atendido,Z,2022
857,2022,Não,Avaliador-11,Avaliador-3,NaN,NaN,84,301,8,2015,...,NaN,NaN,Ametista,6.9,RA-858,Mantido na Fase atual,Mantido na Fase atual,Requer avaliação,Z,2022
858,2022,Não,Avaliador-11,Avaliador-3,NaN,NaN,15,58,4,2015,...,NaN,NaN,Topázio,8.4,RA-859,Promovido de Fase,Mantido na Fase atual,Não atendido,Z,2022
859,2022,Não,Avaliador-11,Avaliador-3,NaN,NaN,29,104,6,2015,...,NaN,NaN,Topázio,7.2,RA-860,Mantido na Fase atual,Mantido na Fase atual,Não atendido,Z,2022

In [ ]:
dados_2023_padronizado

,Ano ingresso,Atingiu PV,Avaliador1,Avaliador2,Avaliador3,Avaliador4,Cf,Cg,Ct,Data de Nasc,...,Pedra 20,Pedra 21,Pedra atual,Por,RA,Rec Av1,Rec Av2,Rec Psicologia,Turma,ano
0,2023,NaN,Avaliador-11,Avaliador-2,NaN,NaN,NaN,NaN,NaN,6/17/2015,...,NaN,NaN,Topázio,9.4,RA-861,NaN,NaN,NaN,ALFA A - G0/G1,2023
1,2023,NaN,Avaliador-11,Avaliador-2,NaN,NaN,NaN,NaN,NaN,5/31/2014,...,NaN,NaN,Topázio,9.2,RA-862,NaN,NaN,NaN,ALFA A - G0/G1,2023
2,2023,NaN,Avaliador-11,Avaliador-2,NaN,NaN,NaN,NaN,NaN,2/25/2016,...,NaN,NaN,Quartzo,5.5,RA-863,NaN,NaN,NaN,ALFA A - G0/G1,2023
3,2023,NaN,Avaliador-11,Avaliador-2,NaN,NaN,NaN,NaN,NaN,2015-12-03 00:00:00,...,NaN,NaN,Ametista,5.5,RA-864,NaN,NaN,NaN,ALFA A - G0/G1,2023
4,2023,NaN,Avaliador-11,Avaliador-2,NaN,NaN,NaN,NaN,NaN,11/13/2014,...,NaN,NaN,Topázio,7.5,RA-865,NaN,NaN,NaN,ALFA A - G0/G1,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/17/2005,...,Ametista,Ametista,NaN,NaN,RA-2,NaN,NaN,NaN,8E,2023
1010,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/23/2004,...,NaN,NaN,NaN,NaN,RA-1271,NaN,NaN,NaN,8E,2023
1011,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-04-11 00:00:00,...,NaN,NaN,NaN,NaN,RA-1272,NaN,NaN,NaN,8E,2023
1012,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/29/2005,...,NaN,NaN,NaN,NaN,RA-1273,NaN,NaN,NaN,8E,2023
1013,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005-07-10 00:00:00,...,NaN,NaN,NaN,NaN,RA-1274,NaN,NaN,NaN,8E,2023

In [ ]:
dados = pd.concat([dados_2022_padronizado ,dados_2023_padronizado ,dados_2024_padronizado ])

In [ ]:
dados[['ano']].groupby('ano').agg({'ano': 'count'})

       ano
ano
2022   860
2023  1014
2024  1156

In [ ]:
dados.to_excel('dados_tech_5.xlsx')

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

minmax_cols = [
    "IAA", "IAN", "IDA", "IEG",
    "IPS", "IPV", "Mat", "Por",
    "Ing"
]

scaler = MinMaxScaler()

dados[minmax_cols] = scaler.fit_transform(dados[minmax_cols])

In [ ]:
dados.to_excel('dados_tech_6.xlsx')